version: '3.8'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cloud123
    ports:
      - "27017:27017"
    volumes:
      - /Users/ryanviana/Developer/thu-morning-cloud/crypto-prices/data/db:/data/db
    networks:
      - mongo-compose-network
    restart: always

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: cloud123
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - mongo-compose-network
    restart: always

networks:
  mongo-compose-network:
    driver: bridge
